version: '3.8'
services:
  postgres:
    image: postgres:14
    hostname: postgres
    container_name: keyleum
    restart: always
    ports:
      - 5435:5432
    expose:
      - "5435"
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: keyleum-db