export const events = {
  LESSOR_DELETED: 'LESSOR_DELETED',
  TENANT_DELETED: 'TENANT_DELETED',
  ORGANISATION_DELETED: 'ORGANISATION_DELETED',
  LESSOR_NOT_DELETED: 'LESSOR_NOT_DELETED',
  TENANT_NOT_DELETED: 'LESSOR_NOT_DELETED',
  ORGANISATION_NOT_DELETED: 'LESSOR_NOT_DELETED',
};
